### ISSUE TITLE
Remove JSONStream

### ISSUE THREAD

**Issue by trygve-lie** [asset-pipe/asset-pipe-js-reader#26]
This module assume that the input streams are JSON and parsed the input with JSONStream.parse(). 

asset-pipe-js-writer does not create JSON so these are not 1to1 compatible. asset-pipe-js-writer returns an object stream. It should be possible to plug this directly into this module. Iow; remove JSONStream.parse().

**Comment by SimenB** [comment]
Fixed in 48e246b5725a404f445fb27f9ef77355df562bc3
